/* ============================================================
   NovaCart product catalog.
   In production, replace this with a fetch from your supplier
   API (AliExpress/CJ Dropshipping/Spocket) — see README.md.
   trendScore (0–100) drives the AI ranking + 🔥 badges.
   ============================================================ */

const PRODUCTS = [
  {
    id: "galaxy-projector",
    name: "Aurora Galaxy Star Projector",
    category: "home",
    price: 39.99,
    compareAt: 59.99,
    rating: 4.8,
    reviews: 2314,
    emoji: "🌌",
    hue: 258,
    trendScore: 96,
    desc: "Fills any room with drifting nebula clouds and starfields. App-controlled, 21 lighting modes, built-in white-noise speaker.",
  },
  {
    id: "led-strip",
    name: "SmartGlow RGB LED Strip (10m)",
    category: "home",
    price: 24.99,
    compareAt: 39.99,
    rating: 4.7,
    reviews: 5102,
    emoji: "💡",
    hue: 190,
    trendScore: 88,
    desc: "Music-sync RGB lighting with voice control. Works with Alexa & Google Home. Cut-to-fit with adhesive backing.",
  },
  {
    id: "mini-printer",
    name: "PocketPrint Thermal Photo Printer",
    category: "tech",
    price: 34.99,
    compareAt: 54.99,
    rating: 4.6,
    reviews: 1876,
    emoji: "🖨️",
    hue: 330,
    trendScore: 91,
    desc: "Inkless pocket printer for photos, labels, and study notes. Bluetooth, 200+ sticker templates in the app.",
  },
  {
    id: "magsafe-stand",
    name: "OrbitFold 3-in-1 Charging Station",
    category: "tech",
    price: 45.99,
    compareAt: 69.99,
    rating: 4.9,
    reviews: 3421,
    emoji: "🔋",
    hue: 215,
    trendScore: 94,
    desc: "Charges phone, watch, and earbuds at once. Foldable travel design with fast-charge coils.",
  },
  {
    id: "smart-bottle",
    name: "HydraSense Smart Water Bottle",
    category: "fitness",
    price: 29.99,
    compareAt: 44.99,
    rating: 4.5,
    reviews: 987,
    emoji: "🚰",
    hue: 175,
    trendScore: 78,
    desc: "Glows to remind you to drink. Tracks intake via app, keeps drinks cold 24h. BPA-free steel.",
  },
  {
    id: "massage-gun",
    name: "PulseTherapy Mini Massage Gun",
    category: "fitness",
    price: 49.99,
    compareAt: 89.99,
    rating: 4.8,
    reviews: 4210,
    emoji: "💆",
    hue: 10,
    trendScore: 90,
    desc: "Pro-grade percussion in a 480g body. 4 heads, 5 speeds, whisper-quiet, USB-C fast charge.",
  },
  {
    id: "resistance-bands",
    name: "FlexPro Resistance Band Set",
    category: "fitness",
    price: 19.99,
    compareAt: 34.99,
    rating: 4.6,
    reviews: 2765,
    emoji: "🏋️",
    hue: 145,
    trendScore: 72,
    desc: "5 stackable bands up to 150 lbs with handles, ankle straps, and door anchor. Full home gym in a pouch.",
  },
  {
    id: "ice-roller",
    name: "GlacierGlow Ice Facial Roller",
    category: "beauty",
    price: 16.99,
    compareAt: 27.99,
    rating: 4.7,
    reviews: 1543,
    emoji: "🧊",
    hue: 200,
    trendScore: 83,
    desc: "De-puffs and tightens in 2 minutes. Stays cold for hours — the viral morning-routine staple.",
  },
  {
    id: "scalp-brush",
    name: "SereneScalp Massager Shampoo Brush",
    category: "beauty",
    price: 12.99,
    compareAt: 19.99,
    rating: 4.8,
    reviews: 6231,
    emoji: "🧖",
    hue: 300,
    trendScore: 86,
    desc: "Soft silicone bristles that exfoliate and boost circulation. Waterproof, ergonomic grip.",
  },
  {
    id: "led-mask",
    name: "LumiDerm LED Therapy Mask",
    category: "beauty",
    price: 79.99,
    compareAt: 129.99,
    rating: 4.5,
    reviews: 892,
    emoji: "🎭",
    hue: 350,
    trendScore: 89,
    desc: "7-color light therapy for clearer, firmer skin. Clinically-inspired wavelengths, 10-minute sessions.",
  },
  {
    id: "pet-fountain",
    name: "PurrStream Pet Water Fountain",
    category: "pets",
    price: 27.99,
    compareAt: 42.99,
    rating: 4.7,
    reviews: 3188,
    emoji: "🐱",
    hue: 165,
    trendScore: 81,
    desc: "2.4L whisper-quiet fountain with triple filtration. Keeps pets hydrated and vets happy.",
  },
  {
    id: "pet-camera",
    name: "PawWatch Treat-Tossing Camera",
    category: "pets",
    price: 64.99,
    compareAt: 99.99,
    rating: 4.6,
    reviews: 1420,
    emoji: "🐶",
    hue: 35,
    trendScore: 87,
    desc: "1080p camera with 2-way audio and a treat launcher you control from anywhere. Bark alerts included.",
  },
  {
    id: "groom-glove",
    name: "FurAway Grooming Gloves (Pair)",
    category: "pets",
    price: 11.99,
    compareAt: 18.99,
    rating: 4.5,
    reviews: 5470,
    emoji: "🧤",
    hue: 120,
    trendScore: 69,
    desc: "Turns petting into de-shedding. 255 silicone tips lift loose fur from cats and dogs — they love it.",
  },
  {
    id: "earbuds",
    name: "AeroBuds Pro ANC Earbuds",
    category: "tech",
    price: 54.99,
    compareAt: 89.99,
    rating: 4.7,
    reviews: 7203,
    emoji: "🎧",
    hue: 240,
    trendScore: 93,
    desc: "Active noise cancelling, 36h battery with case, wireless charging, IPX5 sweat-proof.",
  },
  {
    id: "sunset-lamp",
    name: "GoldenHour Sunset Projection Lamp",
    category: "home",
    price: 21.99,
    compareAt: 34.99,
    rating: 4.6,
    reviews: 4894,
    emoji: "🌅",
    hue: 25,
    trendScore: 84,
    desc: "The viral photography lamp. 180° rotating head casts a perfect golden-hour glow, anytime.",
  },
  {
    id: "desk-vacuum",
    name: "CrumbBot Mini Desk Vacuum",
    category: "tech",
    price: 14.99,
    compareAt: 24.99,
    rating: 4.4,
    reviews: 2011,
    emoji: "🌪️",
    hue: 280,
    trendScore: 74,
    desc: "Palm-sized USB-C vacuum for keyboards, desks, and car consoles. Surprisingly powerful, oddly satisfying.",
  },
];
